import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <div className='text-[12px] -mt-10 flex justify-center space-x-4'>
   <div>Copyright © 2023 Usman Ashraf </div>
   <div><Link href={"https://github.com/usmanashrf"}> https://github.com/usmanashrf</Link></div>
   </div>
    </html>
  )
}
